### PR TITLE
Obvious Fix: Added spring-boot-configuration-processor

### LINKED ISSUE #247: @ConfigurationProperties metadata missing from jar file
It's really easy to generate it. Just add the configuration processor.

### PR DESCRIPTION
**Pull request by iNikem**
To generate @ConfigurationProperties metadata

Fixes #247

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@iNikem Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=310)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=310) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by iNikem** [comment]
Should I sign CLA or this qualifies as Obvious fix?

**Comment by sobychacko** [comment]
@iNikem please sign the CLA - then we can review and merge.

**Comment by pivotal-issuemaster** [comment]
@iNikem Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=310)!

**Comment by iNikem** [comment]
@sobychacko done

**Pull request closed without merging**
