### PR TITLE
Actuator health for Kafka-streams binder

### PR DESCRIPTION
**Pull request by arnaudjardine**
Add health indicator to check the state of the underlying KStream threads.

### CODE REVIEW

**Comment by sobychacko** [comment]
@arnaudjardine Thank you for the PR. We will start reviewing it soon.

**Comment by sobychacko** [comment]
@arnaudjardine Could you add a section in the docs explaining how the health indicator works for Kafka Streams binder? You may want to provide some details about the available health options and how a user enables them in the application etc.

**Comment by arnaudjardine** [comment]
@sobychacko I've added the documentation. Please let me know if it's enough. Thanks.

**Comment by sobychacko** [comment]
@arnaudjardine I noticed that some tests have started to fail consistently on the PR branch. If I remove the test you added for the health check, then they pass. Did you see this behavior? Could you take a look and make any necessary changes?

**Comment by arnaudjardine** [comment]
@sobychacko I tried to reproduce the issue you've mentioned without success. I tried to build multiple times and into a docker image just to be sure but the build complete successfully.
My env: Ubuntu 18.04.1.LTS, JDK 8.0.201, Maven 3.5.2
Can you share with me the build logs please ?

Thanks

**Comment by sobychacko** [comment]
Hi @arnaudjardine Here are the errors that I am getting. I first thought it could be something on my environment, but there are other people getting the same errors. 

```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.springframework.cloud.stream.binder.kafka.streams.serde.CompositeNonNativeSerdeTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DeserializationErrorHandlerByKafkaTests$DeserializationByKafkaAndDlqTests.test:138 [Incorrect results returned] expected:<[1]> but was:<[0]>
[ERROR]   KafkaStreamsNativeEncodingDecodingTests$NativeEncodingDecodingEnabledTests.test:123 [Incorrect results returned] expected:<[1]> but was:<[0]>
[INFO]
[ERROR] Tests run: 21, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for spring-cloud-stream-binder-kafka-parent 2.2.0.BUILD-SNAPSHOT:
[INFO]
[INFO] spring-cloud-stream-binder-kafka-parent ............ SUCCESS [ 18.716 s]
[INFO] spring-cloud-stream-binder-kafka-core .............. SUCCESS [ 22.893 s]
[INFO] spring-cloud-stream-binder-kafka ................... SUCCESS [04:30 min]
[INFO] spring-cloud-starter-stream-kafka .................. SUCCESS [  0.446 s]
[INFO] spring-cloud-stream-binder-kafka-streams ........... FAILURE [04:18 min]
[INFO] spring-cloud-stream-binder-kafka-docs .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:32 min
[INFO] Finished at: 2019-02-13T12:25:39-08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by arnaudjardine** [comment]
Hi @sobychacko I was finally able to reproduced by adding a test and I completely refactor them. It should work better now.

**Comment by sobychacko** [comment]
@arnaudjardine Thank you for this PR. Squashed your commits and merged upstream. Hoping to see more PR's from you.
I created a related issue [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/550). Feel free to grab it and send a PR for that. It should be easy enough to add tests for that, as you already provided the infrastructure through this PR.

**Pull request closed without merging**
