### PR TITLE
JUnit test fix/polishing/refactoring

### PR DESCRIPTION
**Pull request by UltimaPhoenix**
Fixed some assertions. 
Replace the usage of a deprecated method with the last one.
Some other minor changes in tests assertions.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@UltimaPhoenix Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=393)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=393) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@UltimaPhoenix Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=393)!

**Comment by olegz** [comment]
I've modified the title to make it more clear that this is more of a refactoring/polishing as I don't see any fixes. Other then that thank you for the contribution.

@sobychacko +1 from me

**Comment by UltimaPhoenix** [comment]
I fixed the test that previously doesn't test nothing.

```
assertThat(cr.key().equals(123));
...
assertThat(aLong.equals(1L));
```

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/393/commits/a6e55a0b03840cd4c41eb7b8affd214e8df4ad12

**Comment by sobychacko** [comment]
Thank you for the PR. More contributions are welcomed.
Looks good to me. Polished and merged upstream.

**Pull request closed without merging**
