### PR TITLE
Kafka 0.9 upgrade 

### PR DESCRIPTION
**Pull request by sobychacko**
Will keep more changes as we go along, but can review this.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sobychacko Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=13)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=13) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sobychacko Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=13)!

**Comment by mbogoevici** [comment]
Squashed, closed via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/1bf14ac3909b0ec097e2b2a2c10fb3c96d4b9cc2

**Comment by Kenvelo90** [comment]
@sobychacko 
Does it mean that we can dynamically add Kafka consumers in v1.1.0.RELEASE?

According to spring data flow latest documentation:
"Currently, this is not supported with the Kafka binder (based on the 0.8 simple consumer at the time of the release), as well as partitioned streams, for which the suggested workaround is redeploying the stream with an updated number of instances. Both cases require a static consumer set up based on information about the total instance count and current instance index, a limitation intended to be addressed in future releases. For example, Kafka 0.9 and higher provides good infrastructure for scaling applications dynamically and will be available as an alternative to the current Kafka 0.8 based binder in the near future. One specific concern regarding scaling partitioned streams is the handling of local state, which is typically reshuffled as the number of instances is changed. This is also intended to be addressed in the future versions, by providing first class support for local state management."

Reference:
http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#arch-runtime-scaling

Great work it's an awesome integration!

**Pull request closed without merging**
