### PR TITLE
set Kafka ackMode to MANUAL if autoCommitOffset = false

### PR DESCRIPTION
**Pull request by mnadelson**
This is a fix for JIRA issue #44

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mnadelson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=46)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=46) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by sobychacko** [comment]
@mnadelson Can you please sign the CLA?

**Comment by mnadelson** [comment]
I have signed the CLA.  Do I need to do something to resubmit the pull request?

**Comment by pivotal-issuemaster** [comment]
@mnadelson Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-stream-binder-kafka&pullRequestId=46)!

**Comment by mbogoevici** [comment]
Thanks @mnadelson for the contribution!

**Comment by sobychacko** [comment]
rebased, polished, squashed.

LGTM - merged. 

Thanks!!

**Pull request closed without merging**
