### PR TITLE
Allow channel specific group names

### PR DESCRIPTION
**Pull request by Walliee**
- use chanel specific group name over binder level group id/name
config
- use binder level group id/name config if channel group name is
anonymous
- use anonymous group name if binder level group id/name config is
absent

### CODE REVIEW

**Comment by Walliee** [comment]
Fixes #525

**Comment by garyrussell** [comment]
This is a legitimate bug, the `binder.consumer-properties` group.id should **never** win; it violates the semantics of 

>**group**

>The consumer group of the channel. Applies only to inbound bindings. See Consumer Groups.

>Default: null (indicating an anonymous consumer).

In that if there is no group, the consumer **must** be anonymous. Any boot or binding-level setting for `group.id` must be ignored.

This is certainly wrong...

```java
		props.put(ConsumerConfig.GROUP_ID_CONFIG, consumerGroup);

		Map<String, Object> mergedConfig = this.configurationProperties.mergedConsumerConfiguration();
		if (!ObjectUtils.isEmpty(mergedConfig)) {
			props.putAll(mergedConfig);
		}
```
But we can't move it up, because we want most of the other configuration to be applied (overwrite deserializers for example).

The `KafkaBinderConfigurationProperties.mergedConsumerConfiguration()` should filter out any GROUP_ID_CONFIG property, as well as ENABLE_AUTO_COMMIT_CONFIG because that, too would violate binding properties; we never want the kafka-clients to manage the commits). When filtering out such properties, we might want to log a WARN explaining that the setting should be on the binding instead.

**Comment by garyrussell** [comment]
Furthermore, allowing the GROUP_ID_CONFIG to win will violate other component names (error channel etc, which includes the group name), which would be wrong for anon. consumers.

**Comment by Walliee** [comment]
@garyrussell Thanks for the pointers! What you said makes sense, in fact I thought about it too when I originally created this PR. 

I was concerned however that despite this (group.id sourcing from Boot/SCS consumer properties) being unintentional, there might be consumers relying on existing behaviour.

**Comment by garyrussell** [comment]
>I was concerned 

It's a reasonable concern; we generally try to avoid breaking changes, however an existing app relying on a bug would not generally be a concern.

Let's continue the discussion on #525

**Pull request closed without merging**
